services:
  workspace:
    build: .
    ipc: host
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ../:/home/developer/ros2_ws/src:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/runtime:/tmp/runtime
    devices:
      - /dev:/dev
    environment:
      - DISPLAY=host.docker.internal:0
      - "QT_X11_NO_MITSHM=1"
      - XDG_RUNTIME_DIR=/tmp/runtime
